name: life_management_app
description: A comprehensive personal life management system
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.6
  
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  go_router: ^14.2.0
  
  supabase_flutter: ^2.5.6
  
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  dio: ^5.4.3+1
  
  fl_chart: ^0.68.0
  
  flutter_local_notifications: ^17.1.2
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  
  flutter_secure_storage: ^9.2.2
  encrypt: ^5.0.3
  
  image_picker: ^1.1.2
  file_picker: ^8.0.5
  
  intl: ^0.19.0
  uuid: ^4.4.0
  
  shared_preferences: ^2.2.3
  
  permission_handler: ^11.3.1
  
  path_provider: ^2.1.3
  
  local_auth: ^2.2.0
  
  url_launcher: ^6.3.0
  
  connectivity_plus: ^6.0.3
  
  cached_network_image: ^3.3.1
  
  flutter_markdown: ^0.7.3
  
  animations: ^2.0.11
  
  flutter_svg: ^2.0.10+1
  
  flutter_slidable: ^3.1.0
  
  table_calendar: ^3.1.2
  
  flutter_colorpicker: ^1.1.0
  
  flutter_quill: ^9.5.15
  
  audio_waveforms: ^1.0.5
  
  qr_flutter: ^4.1.0
  
  flutter_animate: ^4.5.0
  
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0
  
  riverpod_generator: ^2.4.0
  
  build_runner: ^2.4.11
  
  hive_generator: ^2.0.1
  
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
